# Generated by Django 4.2.7 on 2023-11-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPlante', '0003_measure_datetime_measure_moisture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='id_node',
        ),
        migrations.AddField(
            model_name='measure',
            name='num_node',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='light',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
